export const mockCylinders = [
  {
    id: "cyl-1",
    cylinderType: "domestic" as const,
    capacity: "14.2",
    price: "899.00",
    description: "Standard domestic LPG cylinder for household cooking needs",
    imageUrl: null,
  },
  {
    id: "cyl-2",
    cylinderType: "domestic" as const,
    capacity: "5.0",
    price: "499.00",
    description: "Compact domestic cylinder for small families",
    imageUrl: null,
  },
  {
    id: "cyl-3",
    cylinderType: "commercial" as const,
    capacity: "19.0",
    price: "1499.00",
    description: "Commercial grade cylinder for restaurants and hotels",
    imageUrl: null,
  },
  {
    id: "cyl-4",
    cylinderType: "commercial" as const,
    capacity: "47.5",
    price: "2999.00",
    description: "Large commercial cylinder for industrial kitchens",
    imageUrl: null,
  },
  {
    id: "cyl-5",
    cylinderType: "industrial" as const,
    capacity: "100.0",
    price: "5999.00",
    description: "Industrial grade cylinder for manufacturing units",
    imageUrl: null,
  },
];

export const mockAgencies = [
  {
    id: "agency-1",
    agencyName: "City Gas Distributors",
    address: "123 Main Street, Downtown",
    contactNumber: "+1 234-567-8901",
    email: "citygas@example.com",
  },
  {
    id: "agency-2",
    agencyName: "Metro LPG Services",
    address: "456 Oak Avenue, Midtown",
    contactNumber: "+1 234-567-8902",
    email: "metrolpg@example.com",
  },
  {
    id: "agency-3",
    agencyName: "Sunrise Gas Agency",
    address: "789 Pine Road, Uptown",
    contactNumber: "+1 234-567-8903",
    email: "sunrisegas@example.com",
  },
];

export const mockBookings = [
  {
    id: "book-1",
    customerId: "cust-1",
    agencyId: "agency-1",
    cylinderId: "cyl-1",
    bookingDate: new Date("2024-12-10"),
    deliveryDate: new Date("2024-12-12"),
    status: "delivered" as const,
    bookingType: "regular" as const,
    quantity: 1,
    cylinder: mockCylinders[0],
    agency: mockAgencies[0],
  },
  {
    id: "book-2",
    customerId: "cust-1",
    agencyId: "agency-2",
    cylinderId: "cyl-2",
    bookingDate: new Date("2024-12-14"),
    deliveryDate: new Date("2024-12-16"),
    status: "confirmed" as const,
    bookingType: "regular" as const,
    quantity: 2,
    cylinder: mockCylinders[1],
    agency: mockAgencies[1],
  },
  {
    id: "book-3",
    customerId: "cust-1",
    agencyId: "agency-1",
    cylinderId: "cyl-1",
    bookingDate: new Date("2024-12-15"),
    deliveryDate: null,
    status: "pending" as const,
    bookingType: "emergency" as const,
    quantity: 1,
    cylinder: mockCylinders[0],
    agency: mockAgencies[0],
  },
];

export const mockPayments = [
  {
    id: "pay-1",
    bookingId: "book-1",
    paymentDate: new Date("2024-12-10"),
    amount: "899.00",
    paymentMode: "upi" as const,
    status: "completed",
    booking: mockBookings[0],
  },
  {
    id: "pay-2",
    bookingId: "book-2",
    paymentDate: new Date("2024-12-14"),
    amount: "998.00",
    paymentMode: "card" as const,
    status: "completed",
    booking: mockBookings[1],
  },
];

export const mockSupplies = [
  {
    id: "supply-1",
    agencyId: "agency-1",
    cylinderId: "cyl-1",
    stock: 150,
    cylinder: mockCylinders[0],
  },
  {
    id: "supply-2",
    agencyId: "agency-1",
    cylinderId: "cyl-2",
    stock: 80,
    cylinder: mockCylinders[1],
  },
  {
    id: "supply-3",
    agencyId: "agency-1",
    cylinderId: "cyl-3",
    stock: 45,
    cylinder: mockCylinders[2],
  },
  {
    id: "supply-4",
    agencyId: "agency-1",
    cylinderId: "cyl-4",
    stock: 20,
    cylinder: mockCylinders[3],
  },
  {
    id: "supply-5",
    agencyId: "agency-1",
    cylinderId: "cyl-5",
    stock: 12,
    cylinder: mockCylinders[4],
  },
];

export const mockAgencyBookings = [
  ...mockBookings,
  {
    id: "book-4",
    customerId: "cust-2",
    agencyId: "agency-1",
    cylinderId: "cyl-3",
    bookingDate: new Date("2024-12-13"),
    deliveryDate: new Date("2024-12-15"),
    status: "in_transit" as const,
    bookingType: "regular" as const,
    quantity: 3,
    cylinder: mockCylinders[2],
    agency: mockAgencies[0],
    customer: { name: "Jane Smith", email: "jane@example.com", phoneNumber: "+1 555-123-4567" },
  },
  {
    id: "book-5",
    customerId: "cust-3",
    agencyId: "agency-1",
    cylinderId: "cyl-1",
    bookingDate: new Date("2024-12-16"),
    deliveryDate: null,
    status: "pending" as const,
    bookingType: "subscription" as const,
    quantity: 1,
    cylinder: mockCylinders[0],
    agency: mockAgencies[0],
    customer: { name: "Bob Johnson", email: "bob@example.com", phoneNumber: "+1 555-987-6543" },
  },
];

export const mockStats = {
  totalBookings: 156,
  pendingBookings: 12,
  completedBookings: 138,
  cancelledBookings: 6,
  totalRevenue: 145670,
  monthlyRevenue: 28450,
  averageOrderValue: 934,
  activeCustomers: 89,
  cylindersDelivered: 203,
  pendingDeliveries: 15,
};

export const mockChartData = {
  bookingTrends: [
    { month: "Jul", bookings: 45 },
    { month: "Aug", bookings: 52 },
    { month: "Sep", bookings: 48 },
    { month: "Oct", bookings: 61 },
    { month: "Nov", bookings: 55 },
    { month: "Dec", bookings: 68 },
  ],
  cylinderDistribution: [
    { type: "Domestic 14.2kg", count: 85, fill: "hsl(var(--chart-1))" },
    { type: "Domestic 5kg", count: 45, fill: "hsl(var(--chart-2))" },
    { type: "Commercial 19kg", count: 35, fill: "hsl(var(--chart-3))" },
    { type: "Commercial 47.5kg", count: 18, fill: "hsl(var(--chart-4))" },
    { type: "Industrial 100kg", count: 8, fill: "hsl(var(--chart-5))" },
  ],
  revenueByMonth: [
    { month: "Jul", revenue: 21500 },
    { month: "Aug", revenue: 24800 },
    { month: "Sep", revenue: 22100 },
    { month: "Oct", revenue: 28900 },
    { month: "Nov", revenue: 26400 },
    { month: "Dec", revenue: 31200 },
  ],
};
